packages:
  - apps/*
  - packages/*
  - infra/frontend-cdn

catalog:
  prettier: 2.7.1

overrides:
  "@types/node": 18.6.3
  "tsup>esbuild": 0.15.5
  "vite-plugin-compile-time>esbuild": 0.15.5
  "vite@2>esbuild": 0.15.5
  "vite@3>esbuild": 0.15.5

allowBuilds:
  "@nestjs/core": false
  "@swc/core": true
  bcrypt: true
  core-js: false
  esbuild: true
  sharp: true
  workerd: true

peerDependencyRules:
  allowedVersions:
    "monaco-ace-tokenizer>monaco-editor": 0.33.0
    "react-navi>navi": 0.15.0
    "react-navi>react": 18.2.0
    "vite-plugin-public-path>vite": 3.1.2

patchedDependencies:
  "@vitejs/plugin-legacy@2.0.0": packages/frontend/patches/@vitejs+plugin-legacy+2.0.0.patch
  "fomantic-ui-css@2.8.8": packages/frontend/patches/fomantic-ui-css+2.8.8.patch
  "markdown-it-mentions@1.0.0": packages/frontend/patches/markdown-it-mentions+1.0.0.patch
  "react-navi@0.15.0": packages/frontend/patches/react-navi+0.15.0.patch
  "rollup-plugin-node-polyfills@0.2.1": packages/frontend/patches/rollup-plugin-node-polyfills+0.2.1.patch
  "vite-plugin-html-minifier-terser@2.0.3": packages/frontend/patches/vite-plugin-html-minifier-terser+2.0.3.patch
  "vite-plugin-public-path@1.0.0": packages/frontend/patches/vite-plugin-public-path+1.0.0.patch

strictDepBuilds: true
disallowWorkspaceCycles: true
failIfNoMatch: true
