const{test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),ts=require('typescript');require('reflect-metadata');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2019,module:ts.ModuleKind.CommonJS,esModuleInterop:true,experimentalDecorators:true,emitDecoratorMetadata:true}}).outputText,f);
const{AiService}=require('./ai.service.ts'),{ProblemController}=require('../problem/problem.controller.ts'),{declaredAiPublicHeaderNames}=require('./ai-protocol.ts');
async function fixture(run){const root=fs.mkdtempSync(path.join(os.tmpdir(),'ai-public-header-test-')),old=process.env.HYHOJ_AI_SAMPLE_INPUTS_DIR;process.env.HYHOJ_AI_SAMPLE_INPUTS_DIR=root;let allowed=true,beforeCommit=()=>{};const publicFiles=[],bytes=new Map(),writes=[],problem={id:8,type:'Communication',isPublic:true},user={id:4},sources={'communication.h':'#include <string>\nstd::string Alice(int n);\nint Bob(std::string);\n','private.h':'const int secret=42;','private.cpp':'int secret=42;'};const snapshot={statements:[]},job={state:{protocolExtraSourceFiles:sources,protocolPublicHeaderNames:['communication.h']}};
const problems={userHasPermission:async()=>allowed,getProblemFiles:async(_p,type)=>{assert.equal(type,'AdditionalFile');return publicFiles;},addProblemFilesFromDisk:async(_p,type,files,options)=>{assert.equal(type,'AdditionalFile');assert.equal(options.replaceExisting,false);beforeCommit();assert.equal(typeof options.authorizeCommit,"function");await options.authorize();const manager={};await options.authorizeCommit(manager,_p);await options.noLimit(manager);for(const f of files){assert(!publicFiles.some(x=>x.filename.toLowerCase()===f.filename.toLowerCase()));const uuid='public-'+publicFiles.length;publicFiles.push({filename:f.filename,uuid});bytes.set(uuid,fs.readFileSync(f.path));writes.push(f.filename);}}};const service=new AiService({}, {}, {}, {userHasPrivilege:async()=>false},problems,{}, {downloadFileToPath:async(uuid,target,limit)=>{assert.equal(limit,256*1024);fs.writeFileSync(target,bytes.get(uuid));return bytes.get(uuid).length;}});service.assertJob=service.assertSnapshot=async()=>user;service.authorizeProblemCommit=async(_job,_snapshot,manager,currentProblem)=>{assert(manager);assert.equal(currentProblem,problem);if(!allowed)throw new Error("PERMISSION_DENIED");return user;};
try{await run({service,job,snapshot,problem,user,sources,publicFiles,bytes,writes,problems,deny:()=>allowed=false,beforeCommit:f=>beforeCommit=f,publish:()=>service.publishProtocolHeaders(job,problem,snapshot)});assert.deepEqual(fs.readdirSync(root),[]);}finally{if(old===undefined)delete process.env.HYHOJ_AI_SAMPLE_INPUTS_DIR;else process.env.HYHOJ_AI_SAMPLE_INPUTS_DIR=old;fs.rmSync(root,{recursive:true,force:true});}}
test('only explicitly public generated headers reach ordinary contestant attachment access',()=>fixture(async f=>{await f.publish();assert.deepEqual(f.writes,['communication.h']);assert.equal(f.bytes.get(f.publicFiles[0].uuid).toString(),f.sources['communication.h']);const controller=Object.create(ProblemController.prototype);controller.problemService={findProblemById:async()=>f.problem,userHasPermission:async(_u,_p,permission)=>permission==='View',getProblemMeta:async()=>({id:8}),listProblemFiles:async(_p,type)=>{assert.equal(type,'AdditionalFile');return f.publicFiles;}};controller.userPrivilegeService={userHasPrivilege:async(_u,p)=>p==='DownloadProblemAttachments'};const result=await controller.getProblem({id:9,isAdmin:false},{id:8,additionalFiles:true});assert.deepEqual(result.additionalFiles.map(x=>x.filename),['communication.h']);controller.userPrivilegeService.userHasPrivilege=async()=>false;assert.equal((await controller.getProblem({id:9},{id:8,additionalFiles:true})).error,'PERMISSION_DENIED');}));
test('denied or revoked attachment modification permission publishes nothing',async()=>{await fixture(async f=>{f.deny();await assert.rejects(f.publish(),/PERMISSION_DENIED/);assert.deepEqual(f.writes,[]);});await fixture(async f=>{f.beforeCommit(f.deny);await assert.rejects(f.publish(),/PERMISSION_DENIED/);assert.deepEqual(f.writes,[]);});});
test('same-content headers are reused and differing or case-only conflicts never overwrite',async()=>{await fixture(async f=>{await f.publish();await f.publish();assert.deepEqual(f.writes,['communication.h']);f.bytes.set(f.publicFiles[0].uuid,Buffer.from('existing user header'));await assert.rejects(f.publish(),/FILE_ALREADY_EXISTS/);assert.equal(f.bytes.get(f.publicFiles[0].uuid).toString(),'existing user header');assert.deepEqual(f.writes,['communication.h']);});await fixture(async f=>{f.publicFiles.push({filename:'Communication.h',uuid:'old'});f.bytes.set('old',Buffer.from(f.sources['communication.h']));await assert.rejects(f.publish(),/FILE_ALREADY_EXISTS/);assert.deepEqual(f.writes,[]);});});
test('existing private sources are not published unless the original statement explicitly declares a public header',()=>fixture(async f=>{delete f.job.state.protocolPublicHeaderNames;await f.publish();assert.deepEqual(f.writes,[]);f.snapshot.statements=[{contentSections:[{type:'Text',text:'Use the provided public header `communication.h`. Private helper private.h is not supplied.'}]}];await f.publish();assert.deepEqual(f.writes,['communication.h']);assert.deepEqual(declaredAiPublicHeaderNames([{contentSections:[{type:'Text',text:'```cpp\n// public header private.h\n```'}]}]),[]);}));

test('transactional conflict or quota errors remain clear AI failures without publishing data',async()=>{const{ArchiveError}=require('../archive/safe-zip.ts');for(const code of ['FILE_ALREADY_EXISTS','TOO_MANY_FILES','TOTAL_SIZE_TOO_LARGE'])await fixture(async f=>{f.problems.addProblemFilesFromDisk=async()=>{throw new ArchiveError(code);};await assert.rejects(f.publish(),e=>e.code===code&&e.message===code);assert.deepEqual(f.writes,[]);});});
