const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const ts=require('typescript');
require('reflect-metadata');require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2019,module:ts.ModuleKind.CommonJS,esModuleInterop:true,experimentalDecorators:true,emitDecoratorMetadata:true}}).outputText,f);
const {AiService}=require('./ai.service.ts');const {AiError}=require('./ai.types.ts');const {tutorialCppCandidates,inlineReferenceSamples,hasFloatingOutputTolerance}=require('./ai-reference.ts');
const source='int main(){return 0;}',fence='```cpp\n'+source+'\n```';
test('extract only complete explicitly C++ programs and deduplicate bilingual identical code',()=>{assert.equal(tutorialCppCandidates(fence+'\n'+fence).length,1);for(const text of ['```python\n'+source+'\n```','```cpp\n'+source,'plain '+source,'```cpp\nvoid solve(){}\n```'])assert.deepEqual(tutorialCppCandidates(text),[]);assert.equal(tutorialCppCandidates('~~~~c++\n'+source+'\n~~~~~')[0].code,source);assert.equal(tutorialCppCandidates('```cpp\nvoid Alice(){}\n```',true).length,1);});
test('preserve empty, whitespace-only and CRLF sample bytes without inventing samples',()=>{assert.deepEqual(inlineReferenceSamples([]),[]);assert.deepEqual(inlineReferenceSamples([{inputData:'',outputData:''},{inputData:' \r\n',outputData:'\t\n'}]),[{input:'',output:''},{input:' \r\n',output:'\t\n'}]);});
test('floating output error acceptance requires a special checker, input approximation does not',()=>{const stmt=(text,title='Output')=>[{contentSections:[{type:'Text',sectionTitle:title,text}]}];assert(hasFloatingOutputTolerance(stmt('The answer is accepted with absolute or relative error at most 1e-6.')));assert(hasFloatingOutputTolerance(stmt('答案绝对误差不超过 1e-9。')));assert(!hasFloatingOutputTolerance(stmt('Input includes the relative error measured by a sensor.','Input')));});
function fixture(samples=[{inputData:'1\n',outputData:'2\n'}]) {let permissions=true;const rows=[{id:31,title:'题解-AI',problemId:8}],reads=[];const db={getRepository:()=>({find:async()=>rows,findOneBy:async()=>rows[0]})};const svc=new AiService(db,{},{},{},{},{userHasPermission:async()=>permissions,getDiscussionContent:async(row)=>{reads.push(row.id);return fence;}},{});svc.assertSnapshot=svc.assertJob=async()=>({id:1});svc.checkpoint=async()=>{};svc.prepareSampleFiles=async()=>({files:[]});const job={id:'memory-only',input:{count:5},state:{validatorCode:'int main(){}'}},snapshot={samples,judgeInfo:{},statements:[]},plan={fileIo:null,outputComparison:'tokens',caseSensitive:true};return {svc,job,snapshot,plan,rows,reads,deny:()=>permissions=false,run:()=>svc.tryTutorialReference(job,{id:1},{id:8,type:'Traditional'},snapshot,plan,0,100)};}
test('reuse a permitted tutorial only after sandbox compilation and all sample inputs/outputs validate',async()=>{const f=fixture();f.svc.runSandbox=async(_,r)=>{assert.equal(f.job.state.stdCode,undefined);assert.equal(r.operation,'validate-reference');assert.equal(r.stdCode,source);assert.deepEqual(r.checker,{type:'tokens',caseSensitive:true});assert.deepEqual(r.cases,[]);return{validation:{samplesPassed:1,sampleInputsPassed:1,inputsPassed:0}};};await f.run();assert.equal(f.job.state.stdCode,source);assert.deepEqual(f.job.state.referenceSource,{kind:'tutorial',discussionId:31,sha256:tutorialCppCandidates(fence)[0].sha256,validated:true,samplesPassed:1});});
test('named-file tutorial is validated with its actual file IO, code is never regex-rewritten',async()=>{const f=fixture();f.plan.fileIo={inputFilename:'input.txt',outputFilename:'output.txt'};f.svc.runSandbox=async(_,r)=>{assert.deepEqual(r.stdFileIo,f.plan.fileIo);return{validation:{samplesPassed:1,sampleInputsPassed:1,inputsPassed:0}};};await f.run();assert.deepEqual(f.job.state.stdFileIo,f.plan.fileIo);});
test('compile or sample rejection leaves std unset for model fallback and records a reviewable warning',async()=>{const f=fixture();f.svc.runSandbox=async()=>{const e=new AiError('SANDBOX_GENERATION_FAILED','Reference solution failed sample 1');e.candidateFailure=true;throw e;};await f.run();assert.equal(f.job.state.stdCode,undefined);assert(f.job.state.warnings.includes('TUTORIAL_REFERENCE_REJECTED'));});
test('permission denial skips reading private tutorial contents',async()=>{const f=fixture();f.deny();f.svc.runSandbox=async()=>assert.fail('must not run');await f.run();assert.deepEqual(f.reads,[]);assert.equal(f.job.state.stdCode,undefined);});
test('no samples never treats a tutorial as validated or launches a preflight',async()=>{const f=fixture([]);f.svc.runSandbox=async()=>assert.fail('must not run');await f.run();assert.equal(f.job.state.stdCode,undefined);assert.equal(f.job.state.referenceSource,undefined);assert(f.job.state.warnings.includes('REFERENCE_SAMPLES_UNAVAILABLE'));});
test('invalid validation counts and infrastructure/cancel errors never silently become fallback success',async()=>{const f=fixture();f.svc.runSandbox=async()=>({validation:{samplesPassed:0,sampleInputsPassed:1,inputsPassed:0}});await assert.rejects(f.run(),/INVALID_SANDBOX_RESPONSE/);assert.equal(f.job.state.stdCode,undefined);for(const code of ['JOB_CANCELLED','PERMISSION_DENIED','SANDBOX_UNAVAILABLE','SANDBOX_GENERATION_FAILED']){f.svc.runSandbox=async()=>{throw new AiError(code);};await assert.rejects(f.run(),new RegExp(code));}});
test('std retry removes reference provenance and preserves already published tutorial IDs',()=>{const f=fixture();const state=f.svc.retryState({status:'failed',action:'all',step:'testdata.validate-samples',error:'SANDBOX_GENERATION_FAILED: sample failed',state:{makeCode:source,plan:{},stdCode:source,stdFileIo:{inputFilename:'a.in',outputFilename:'a.out'},referenceSource:{kind:'tutorial'},discussionIds:{zh_CN:31,en_US:32}}},'std');assert.equal(state.stdCode,undefined);assert.equal(state.stdFileIo,undefined);assert.equal(state.referenceSource,undefined);assert.deepEqual(state.discussionIds,{zh_CN:31,en_US:32});assert(state.generationFailure);});
